const data =  [
    {
        isActive: true,
        title: "Developer",
        password: "Gay",
        login: "Glenna",
        userId: "e0a574e1-6e87-4baf-b942-f984d9cd0635",
        createdAt: new Date(),
        updatedAt: new Date(),
    },
    {
        isActive: false,
        title: "Developer",
        password: "Jenkins",
        login: "Morton",
        userId: "46ae661f-99a9-4838-82cc-d76165f00d1a",
        createdAt: new Date(),
        updatedAt: new Date(),
    },
    {
        isActive: false,
        title: "QA",
        password: "Hurley",
        login: "Ilene",
        userId: "d879a4a3-89e5-45f0-ab68-4944fceb3d62",
        createdAt: new Date(),
        updatedAt: new Date(),
    },
    {
        isActive: true,
        title: "Office Manager",
        password: "Mullins",
        login: "Gamble",
        userId: "f7f2c8a3-1978-405e-97ea-1d917888685c",
        createdAt: new Date(),
        updatedAt: new Date(),
    },
    {
        isActive: false,
        title: "Senior Developer",
        password: "Hopper",
        login: "Lorena",
        userId: "0c65ed67-9ecf-4d1d-a221-5e1473767237",
        createdAt: new Date(),
        updatedAt: new Date(),
    },
    {
        isActive: false,
        title: "Director",
        password: "Mills",
        login: "Carly",
        userId: "6501ef69-4dc3-4e35-a224-e6c757d12bfc",
        createdAt: new Date(),
        updatedAt: new Date(),
    },
    {
        isActive: false,
        title: "QA",
        password: "Mcbride",
        login: "Ora",
        userId: "39302125-bc0e-4fae-901c-bd03f856d017",
        createdAt: new Date(),
        updatedAt: new Date(),
    },
    {
        isActive: true,
        title: "QA",
        password: "Benton",
        login: "Stokes",
        userId: "6a034cbd-4c4a-492d-a29b-364c8500cad3",
        createdAt: new Date(),
        updatedAt: new Date(),
    },
    {
        isActive: true,
        title: "Senior Developer",
        password: "Buchanan",
        login: "Pansy",
        userId: "4ef4bf91-7766-445f-ac45-16c29e50a111",
        createdAt: new Date(),
        updatedAt: new Date(),
    },
    {
        isActive: false,
        title: "Senior Developer",
        password: "Salazar",
        login: "Ladonna",
        userId: "926d872f-8439-40d6-b5d3-6caf5a4e5754",
        createdAt: new Date(),
        updatedAt: new Date(),
    },
    {
        isActive: false,
        title: "Developer",
        password: "Mcdonald",
        login: "Helga",
        userId: "11c4c5f9-22ef-4fdd-99fa-354d0f14f0d4",
        createdAt: new Date(),
        updatedAt: new Date(),
    },
    {
        isActive: false,
        title: "Director",
        password: "Houston",
        login: "Sweet",
        userId: "dc0c8a9b-d236-4ddb-82c0-1bd2b9bc629d",
        createdAt: new Date(),
        updatedAt: new Date(),
    },
    {
        isActive: true,
        title: "Senior Developer",
        password: "Hayes",
        login: "Chelsea",
        userId: "4ad4d36e-d77d-4765-acc4-bd4b92dc8a0a",
        createdAt: new Date(),
        updatedAt: new Date(),
    },
    {
        isActive: false,
        title: "Senior Developer",
        password: "Bass",
        login: "Barr",
        userId: "c20e411d-de6c-460c-a319-ed606e1bfb95",
        createdAt: new Date(),
        updatedAt: new Date(),
    },
    {
        isActive: false,
        title: "Senior Developer",
        password: "Williamson",
        login: "Marsh",
        userId: "cdb24955-4de2-4ae2-9419-2dd509027de6",
        createdAt: new Date(),
        updatedAt: new Date(),
    },
    {
        isActive: true,
        title: "QA",
        password: "Arnold",
        login: "Eula",
        userId: "fb476ea8-dc70-4e0b-97a9-56b6418d9493",
        createdAt: new Date(),
        updatedAt: new Date(),
    },
    {
        isActive: false,
        title: "Office Manager",
        password: "Thomas",
        login: "Herring",
        userId: "5471593b-5609-4641-8e4d-aa540edd09fa",
        createdAt: new Date(),
        updatedAt: new Date(),
    },
    {
        isActive: false,
        title: "Senior Developer",
        password: "Molina",
        login: "Huber",
        userId: "72296ff7-07ce-49b1-8ae9-8c04160e17c0",
        createdAt: new Date(),
        updatedAt: new Date(),
    },
    {
        isActive: false,
        title: "Developer",
        password: "Clay",
        login: "Levine",
        userId: "3200924f-1eb7-454f-994f-6fbde5866048",
        createdAt: new Date(),
        updatedAt: new Date(),
    },
    {
        isActive: true,
        title: "Developer",
        password: "Fischer",
        login: "Pugh",
        userId: "8415e512-955e-4375-abdc-7e2b16b29e5d",
        createdAt: new Date(),
        updatedAt: new Date(),
    }
];

module.exports = data;
